"""notification_pipeline

Revision ID: a7b57afdb502
Revises: 5446fe7daa40
Create Date: 2026-07-03 10:47:10.018381
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7b57afdb502'
down_revision: Union[str, None] = '5446fe7daa40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manual_review_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('notification_number', sa.String(length=50), nullable=True),
    sa.Column('notification_date', sa.Date(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('issue_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('date_added', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_updated', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manual_review_queue_notification_date'), 'manual_review_queue', ['notification_date'], unique=False)
    op.create_index(op.f('ix_manual_review_queue_notification_number'), 'manual_review_queue', ['notification_number'], unique=False)
    op.create_table('notifications_processed',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('notification_number', sa.String(length=50), nullable=False),
    sa.Column('notification_date', sa.Date(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.Text(), nullable=True),
    sa.Column('download_status', sa.String(length=20), nullable=True),
    sa.Column('parsing_status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('last_attempt', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_processed_notification_date'), 'notifications_processed', ['notification_date'], unique=False)
    op.create_index(op.f('ix_notifications_processed_notification_number'), 'notifications_processed', ['notification_number'], unique=True)
    op.add_column('banned_medicines', sa.Column('is_fdc', sa.Boolean(), nullable=True))
    op.execute("UPDATE banned_medicines SET is_fdc = FALSE")
    op.alter_column('banned_medicines', 'is_fdc', nullable=False)
    op.add_column('banned_medicines', sa.Column('ingredients', sa.ARRAY(sa.Text()), nullable=True))
    op.add_column('banned_medicines', sa.Column('source_url', sa.Text(), nullable=True))
    op.drop_constraint('uq_medicine_form_strength', 'banned_medicines', type_='unique')
    op.create_unique_constraint('uq_medicine_form_strength_notif', 'banned_medicines', ['generic_name', 'dosage_form', 'strength', 'notification_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_medicine_form_strength_notif', 'banned_medicines', type_='unique')
    op.create_unique_constraint(op.f('uq_medicine_form_strength'), 'banned_medicines', ['generic_name', 'dosage_form', 'strength'], postgresql_nulls_not_distinct=False)
    op.drop_column('banned_medicines', 'source_url')
    op.drop_column('banned_medicines', 'ingredients')
    op.drop_column('banned_medicines', 'is_fdc')
    op.drop_index(op.f('ix_notifications_processed_notification_number'), table_name='notifications_processed')
    op.drop_index(op.f('ix_notifications_processed_notification_date'), table_name='notifications_processed')
    op.drop_table('notifications_processed')
    op.drop_index(op.f('ix_manual_review_queue_notification_number'), table_name='manual_review_queue')
    op.drop_index(op.f('ix_manual_review_queue_notification_date'), table_name='manual_review_queue')
    op.drop_table('manual_review_queue')
    # ### end Alembic commands ###
